// Weapon catalog for duel / deathmatch / gun game. Most guns are hitscan;
// special flags add burst, charge, overheat beams, projectiles, and melee.

export const WEAPONS = {
  pistol: {
    id: 'pistol',
    name: 'Pistol',
    damage: 24,
    pellets: 1,
    rpm: 400,
    auto: false,
    magazine: 12,
    reload: 1.3,
    spread: 0.004,
    bloom: 0.006,
    maxBloom: 0.03,
    bloomDecay: 0.05,
    moveMult: 1.06,
    recoil: 0.9,
    zoom: 1,
    falloffStart: 40,
    falloffEnd: 70,
    falloffMin: 0.7,
    shake: 0.5,
  },
  assault: {
    id: 'assault',
    name: 'Assault Rifle',
    damage: 18,
    pellets: 1,
    rpm: 660,
    auto: true,
    magazine: 30,
    reload: 2.1,
    spread: 0.006,
    bloom: 0.005,
    maxBloom: 0.05,
    bloomDecay: 0.07,
    moveMult: 0.95,
    recoil: 0.7,
    zoom: 1,
    falloffStart: 35,
    falloffEnd: 65,
    falloffMin: 0.65,
    shake: 0.4,
  },
  shotgun: {
    id: 'shotgun',
    name: 'Shotgun',
    damage: 11,
    pellets: 9,
    rpm: 70,
    auto: false,
    magazine: 6,
    reload: 2.8,
    spread: 0.075,
    bloom: 0,
    maxBloom: 0,
    bloomDecay: 0,
    moveMult: 1.0,
    recoil: 2.4,
    zoom: 1,
    falloffStart: 10,
    falloffEnd: 26,
    falloffMin: 0.22,
    shake: 1.3,
  },
  sniper: {
    id: 'sniper',
    name: 'Sniper Rifle',
    damage: 90,
    pellets: 1,
    rpm: 45,
    auto: false,
    magazine: 5,
    reload: 3.0,
    // Hip fire is deliberately unreliable; scoping restores precision.
    spread: 0.04,
    scopedSpread: 0.0006,
    bloom: 0.03,
    maxBloom: 0.09,
    bloomDecay: 0.04,
    moveMult: 0.82,
    recoil: 3.0,
    zoom: 3.2,
    falloffStart: 200,
    falloffEnd: 400,
    falloffMin: 1,
    shake: 1.6,
  },

  // ── Sidearms ──────────────────────────────────────────────────────────
  revolver: {
    id: 'revolver',
    name: 'Revolver',
    damage: 50,
    pellets: 1,
    rpm: 150,
    auto: false,
    magazine: 6,
    reload: 2.5,
    spread: 0.003,
    bloom: 0.012,
    maxBloom: 0.04,
    bloomDecay: 0.04,
    moveMult: 1.04,
    recoil: 2.0,
    zoom: 1,
    falloffStart: 35,
    falloffEnd: 60,
    falloffMin: 0.6,
    shake: 1.1,
  },
  machinepistol: {
    id: 'machinepistol',
    name: 'Machine Pistol',
    damage: 14,
    pellets: 1,
    rpm: 900,
    auto: true,
    magazine: 18,
    reload: 1.5,
    spread: 0.008,
    bloom: 0.009,
    maxBloom: 0.07,
    bloomDecay: 0.06,
    moveMult: 1.08,
    recoil: 0.5,
    zoom: 1,
    falloffStart: 20,
    falloffEnd: 45,
    falloffMin: 0.5,
    shake: 0.3,
  },
  deagle: {
    id: 'deagle',
    name: 'Deagle',
    damage: 55,
    pellets: 1,
    rpm: 180,
    auto: false,
    magazine: 7,
    reload: 2.0,
    spread: 0.005,
    bloom: 0.018,
    maxBloom: 0.06,
    bloomDecay: 0.035,
    moveMult: 0.98,
    recoil: 2.5,
    zoom: 1,
    falloffStart: 30,
    falloffEnd: 55,
    falloffMin: 0.55,
    shake: 1.4,
  },

  // ── SMGs ──────────────────────────────────────────────────────────────
  smg: {
    id: 'smg',
    name: 'SMG',
    damage: 15,
    pellets: 1,
    rpm: 800,
    auto: true,
    magazine: 25,
    reload: 1.8,
    spread: 0.007,
    bloom: 0.006,
    maxBloom: 0.055,
    bloomDecay: 0.07,
    moveMult: 1.1,
    recoil: 0.45,
    zoom: 1,
    falloffStart: 22,
    falloffEnd: 48,
    falloffMin: 0.5,
    shake: 0.3,
  },
  p90: {
    id: 'p90',
    name: 'P90',
    damage: 13,
    pellets: 1,
    rpm: 720,
    auto: true,
    magazine: 50,
    reload: 3.0,
    spread: 0.008,
    bloom: 0.005,
    maxBloom: 0.05,
    bloomDecay: 0.06,
    moveMult: 1.06,
    recoil: 0.4,
    zoom: 1,
    falloffStart: 24,
    falloffEnd: 50,
    falloffMin: 0.48,
    shake: 0.3,
  },
  vector: {
    id: 'vector',
    name: 'Vector',
    damage: 12,
    pellets: 1,
    rpm: 1200,
    auto: true,
    magazine: 15,
    reload: 1.4,
    spread: 0.006,
    bloom: 0.007,
    maxBloom: 0.06,
    bloomDecay: 0.08,
    moveMult: 1.08,
    recoil: 0.35,
    zoom: 1,
    falloffStart: 18,
    falloffEnd: 40,
    falloffMin: 0.45,
    shake: 0.25,
  },

  // ── Rifles ────────────────────────────────────────────────────────────
  battlerifle: {
    id: 'battlerifle',
    name: 'Battle Rifle',
    damage: 22,
    pellets: 1,
    rpm: 550,
    auto: true,
    magazine: 30,
    reload: 2.3,
    spread: 0.007,
    bloom: 0.007,
    maxBloom: 0.06,
    bloomDecay: 0.06,
    moveMult: 0.92,
    recoil: 1.0,
    zoom: 1,
    falloffStart: 32,
    falloffEnd: 60,
    falloffMin: 0.6,
    shake: 0.6,
  },
  burstrifle: {
    id: 'burstrifle',
    name: 'Burst Rifle',
    damage: 28,
    pellets: 1,
    rpm: 900,
    auto: false,
    magazine: 24,
    reload: 2.0,
    spread: 0.004,
    bloom: 0.004,
    maxBloom: 0.035,
    bloomDecay: 0.06,
    moveMult: 0.96,
    recoil: 0.6,
    zoom: 1,
    falloffStart: 35,
    falloffEnd: 65,
    falloffMin: 0.65,
    shake: 0.5,
    burst: 3,
    burstCooldown: 0.35,
  },
  dmr: {
    id: 'dmr',
    name: 'DMR',
    damage: 42,
    pellets: 1,
    rpm: 260,
    auto: false,
    magazine: 10,
    reload: 2.2,
    spread: 0.003,
    bloom: 0.008,
    maxBloom: 0.04,
    bloomDecay: 0.05,
    moveMult: 0.9,
    recoil: 1.2,
    zoom: 1.5,
    falloffStart: 50,
    falloffEnd: 90,
    falloffMin: 0.75,
    shake: 0.7,
  },
  carbine: {
    id: 'carbine',
    name: 'Carbine',
    damage: 16,
    pellets: 1,
    rpm: 720,
    auto: true,
    magazine: 25,
    reload: 1.6,
    spread: 0.006,
    bloom: 0.005,
    maxBloom: 0.045,
    bloomDecay: 0.07,
    moveMult: 1.04,
    recoil: 0.55,
    zoom: 1,
    falloffStart: 30,
    falloffEnd: 58,
    falloffMin: 0.6,
    shake: 0.35,
  },

  // ── Shotguns ──────────────────────────────────────────────────────────
  autoshotgun: {
    id: 'autoshotgun',
    name: 'Auto Shotgun',
    damage: 8,
    pellets: 7,
    rpm: 200,
    auto: true,
    magazine: 8,
    reload: 2.5,
    spread: 0.08,
    bloom: 0.01,
    maxBloom: 0.04,
    bloomDecay: 0.05,
    moveMult: 0.94,
    recoil: 1.8,
    zoom: 1,
    falloffStart: 8,
    falloffEnd: 22,
    falloffMin: 0.2,
    shake: 1.0,
  },
  slugshotgun: {
    id: 'slugshotgun',
    name: 'Slug Shotgun',
    damage: 65,
    pellets: 1,
    rpm: 80,
    auto: false,
    magazine: 5,
    reload: 2.5,
    spread: 0.012,
    bloom: 0.015,
    maxBloom: 0.05,
    bloomDecay: 0.04,
    moveMult: 0.95,
    recoil: 2.2,
    zoom: 1,
    falloffStart: 20,
    falloffEnd: 50,
    falloffMin: 0.45,
    shake: 1.2,
  },
  doublebarrel: {
    id: 'doublebarrel',
    name: 'Double Barrel',
    damage: 14,
    pellets: 12,
    rpm: 180,
    auto: false,
    magazine: 2,
    reload: 2.8,
    spread: 0.09,
    bloom: 0.02,
    maxBloom: 0.05,
    bloomDecay: 0.04,
    moveMult: 0.96,
    recoil: 3.0,
    zoom: 1,
    falloffStart: 6,
    falloffEnd: 18,
    falloffMin: 0.18,
    shake: 1.5,
  },

  // ── Snipers ───────────────────────────────────────────────────────────
  scout: {
    id: 'scout',
    name: 'Scout',
    damage: 65,
    pellets: 1,
    rpm: 70,
    auto: false,
    magazine: 10,
    reload: 2.5,
    spread: 0.03,
    scopedSpread: 0.001,
    bloom: 0.02,
    maxBloom: 0.06,
    bloomDecay: 0.05,
    moveMult: 0.95,
    recoil: 1.8,
    zoom: 2.4,
    falloffStart: 150,
    falloffEnd: 350,
    falloffMin: 0.9,
    shake: 1.0,
  },
  awp: {
    id: 'awp',
    name: 'AWP',
    damage: 150,
    pellets: 1,
    rpm: 30,
    auto: false,
    magazine: 3,
    reload: 3.5,
    spread: 0.05,
    scopedSpread: 0.0004,
    bloom: 0.04,
    maxBloom: 0.1,
    bloomDecay: 0.03,
    moveMult: 0.75,
    recoil: 4.0,
    zoom: 4.0,
    falloffStart: 250,
    falloffEnd: 500,
    falloffMin: 1,
    shake: 2.0,
  },

  // ── Heavy ─────────────────────────────────────────────────────────────
  lmg: {
    id: 'lmg',
    name: 'LMG',
    damage: 16,
    pellets: 1,
    rpm: 600,
    auto: true,
    magazine: 80,
    reload: 4.5,
    spread: 0.009,
    bloom: 0.004,
    maxBloom: 0.045,
    bloomDecay: 0.04,
    moveMult: 0.78,
    recoil: 0.6,
    zoom: 1,
    falloffStart: 30,
    falloffEnd: 60,
    falloffMin: 0.6,
    shake: 0.5,
  },
  minigun: {
    id: 'minigun',
    name: 'Minigun',
    damage: 10,
    pellets: 1,
    rpm: 1800,
    auto: true,
    magazine: 150,
    reload: 5.0,
    spread: 0.04,
    bloom: 0.002,
    maxBloom: 0.065,
    bloomDecay: 0.03,
    moveMult: 0.65,
    recoil: 0.15,
    zoom: 1,
    falloffStart: 20,
    falloffEnd: 45,
    falloffMin: 0.4,
    shake: 0.2,
  },

  // ── Exotic / Special ──────────────────────────────────────────────────
  crossbow: {
    id: 'crossbow',
    name: 'Crossbow',
    damage: 120,
    pellets: 1,
    rpm: 40,
    auto: false,
    magazine: 1,
    reload: 3.0,
    spread: 0.002,
    bloom: 0,
    maxBloom: 0,
    bloomDecay: 0,
    moveMult: 0.92,
    recoil: 1.5,
    zoom: 1,
    falloffStart: 60,
    falloffEnd: 120,
    falloffMin: 0.8,
    shake: 0.8,
  },
  sawedoff: {
    id: 'sawedoff',
    name: 'Sawed-Off',
    damage: 15,
    pellets: 16,
    rpm: 120,
    auto: false,
    magazine: 2,
    reload: 2.5,
    spread: 0.14,
    bloom: 0,
    maxBloom: 0,
    bloomDecay: 0,
    moveMult: 1.05,
    recoil: 3.5,
    zoom: 1,
    falloffStart: 4,
    falloffEnd: 12,
    falloffMin: 0.1,
    shake: 1.8,
  },
  leveraction: {
    id: 'leveraction',
    name: 'Lever Action',
    damage: 38,
    pellets: 1,
    rpm: 120,
    auto: false,
    magazine: 8,
    reload: 2.8,
    spread: 0.005,
    bloom: 0.008,
    maxBloom: 0.035,
    bloomDecay: 0.06,
    moveMult: 0.98,
    recoil: 1.4,
    zoom: 1,
    falloffStart: 35,
    falloffEnd: 70,
    falloffMin: 0.7,
    shake: 0.9,
  },

  // ── New-mechanic weapons ──────────────────────────────────────────────
  bow: {
    id: 'bow',
    name: 'Bow',
    damage: 85,
    pellets: 1,
    rpm: 60,
    auto: false,
    magazine: 1,
    reload: 0.5,
    spread: 0.06,
    bloom: 0,
    maxBloom: 0,
    bloomDecay: 0,
    moveMult: 0.85,
    recoil: 0.8,
    zoom: 1,
    falloffStart: 40,
    falloffEnd: 80,
    falloffMin: 0.6,
    shake: 0.6,
    charge: true,
    chargeTime: 1.2,
    minDamageMult: 0.25,
    chargeSpreadMult: 0.08,
    // Arrows are true projectiles: they drop with gravity, and launch speed
    // scales with how far the bow was drawn (Minecraft-style).
    projectile: true,
    projSpeed: 42,
    projGravity: 9,
    projArc: 0,
  },
  laser: {
    id: 'laser',
    name: 'Laser Gun',
    damage: 3,
    pellets: 1,
    rpm: 3600,
    auto: true,
    magazine: 999,
    reload: 0,
    spread: 0.005,
    bloom: 0,
    maxBloom: 0,
    bloomDecay: 0,
    moveMult: 0.9,
    recoil: 0,
    zoom: 1,
    falloffStart: 30,
    falloffEnd: 60,
    falloffMin: 0.5,
    shake: 0.05,
    beam: true,
    overheat: true,
    heatPerTick: 0.012,
    heatDecay: 0.02,
    overheatCooldown: 2.0,
  },
  poopgun: {
    id: 'poopgun',
    name: 'Poop',
    damage: 25,
    pellets: 1,
    rpm: 90,
    auto: false,
    magazine: 4,
    reload: 2.5,
    spread: 0.01,
    bloom: 0,
    maxBloom: 0,
    bloomDecay: 0,
    moveMult: 0.95,
    recoil: 1.0,
    zoom: 1,
    falloffStart: 100,
    falloffEnd: 100,
    falloffMin: 1,
    shake: 0.7,
    projectile: true,
    projSpeed: 22,
    projGravity: 15,
    hazardRadius: 2.5,
    hazardDps: 20,
    hazardDuration: 5,
  },
  pee: {
    id: 'pee',
    name: 'Pee',
    damage: 4,
    pellets: 1,
    rpm: 900,
    auto: true,
    magazine: 60,
    reload: 3.0,
    spread: 0.02,
    bloom: 0,
    maxBloom: 0,
    bloomDecay: 0,
    moveMult: 1.0,
    recoil: 0,
    zoom: 1,
    falloffStart: 4,
    falloffEnd: 9,
    falloffMin: 0.3,
    shake: 0,
    beam: true,
    stream: true,
    range: 9,
  },
  fahgun: {
    id: 'fahgun',
    name: 'FAHH Gun',
    damage: 75,
    pellets: 1,
    rpm: 45,
    auto: false,
    magazine: 1,
    reload: 2.6,
    spread: 0.005,
    bloom: 0,
    maxBloom: 0,
    bloomDecay: 0,
    moveMult: 0.85,
    recoil: 2.4,
    zoom: 1,
    falloffStart: 100,
    falloffEnd: 100,
    falloffMin: 1,
    shake: 1.4,
    projectile: true,
    projSpeed: 34,
    projGravity: 4,
    projArc: 0,
    explodeRadius: 4,
    explodeDamage: 70,
  },
  knife: {
    id: 'knife',
    name: 'Knife',
    damage: 200,
    pellets: 1,
    rpm: 120,
    auto: false,
    magazine: 999,
    reload: 0,
    spread: 0,
    bloom: 0,
    maxBloom: 0,
    bloomDecay: 0,
    moveMult: 1.15,
    recoil: 0,
    zoom: 1,
    falloffStart: 100,
    falloffEnd: 100,
    falloffMin: 1,
    shake: 0.3,
    melee: true,
    range: 2.5,
  },
};

export const WEAPON_IDS = Object.keys(WEAPONS);

/** Deathmatch primary choices — pistol is always the fixed secondary. */
export const PRIMARY_WEAPON_IDS = WEAPON_IDS.filter((id) => id !== 'pistol');
export const SECONDARY_WEAPON_ID = 'pistol';
export const DEFAULT_PRIMARY_WEAPON_ID = 'assault';

/** All weapon IDs eligible for Gun Game (knife excluded — always last). */
export const GUNGAME_POOL = WEAPON_IDS.filter((id) => id !== 'knife');

export function isPrimaryWeaponId(id) {
  return PRIMARY_WEAPON_IDS.includes(id);
}

export function weaponById(id) {
  return WEAPONS[id] || WEAPONS.pistol;
}

export function shotSpread(weapon, bloom = 0, zooming = false, chargeFrac = 1) {
  const base = zooming
    ? (weapon.scopedSpread ?? weapon.spread * 0.25)
    : weapon.spread;
  const chargeScale = weapon.charge
    ? 1 - chargeFrac * (1 - (weapon.chargeSpreadMult ?? 0.1))
    : 1;
  const bloomPart = zooming ? bloom * 0.25 : bloom;
  return base * chargeScale + bloomPart;
}

export const HEADSHOT_MULT = 1.8;

export function randomWeaponId(rand = Math.random) {
  return WEAPON_IDS[Math.floor(rand() * WEAPON_IDS.length)];
}

export function shotInterval(weapon) {
  return 60 / weapon.rpm;
}

export function damageAtRange(weapon, distance) {
  if (distance <= weapon.falloffStart) return weapon.damage;
  if (distance >= weapon.falloffEnd) return weapon.damage * weapon.falloffMin;
  const t = (distance - weapon.falloffStart) / (weapon.falloffEnd - weapon.falloffStart);
  return weapon.damage * (1 - t * (1 - weapon.falloffMin));
}

export function chargeDamageMult(weapon, fraction) {
  if (!weapon.charge) return 1;
  const min = weapon.minDamageMult ?? 0.25;
  return min + fraction * (1 - min);
}
